let games=[],sources=[],session=[],savedSessions=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const val=id=>document.getElementById(id)?.value||'';
const setVal=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v??''};
async function init(){
 try{
  const r=await fetch('data/games.json',{cache:'no-store'});if(!r.ok)throw Error('games.json');games=await r.json();
  const s=await fetch('data/sources.json',{cache:'no-store'});sources=s.ok?await s.json():[];
  savedSessions=JSON.parse(localStorage.getItem('motorlab_sessions')||'[]');
  if($('#totalGames'))$('#totalGames').textContent=games.length;
  buildFilters();renderGames();renderSaved();renderSources();setVal('sessionDate',new Date().toISOString().slice(0,10));
 }catch(e){console.error(e);if($('#resultSummary'))$('#resultSummary').textContent='Error al cargar el catálogo';$('#empty')?.classList.remove('hidden')}
}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function materialTag(m){const x=norm(m);if(x.includes('sin material')||x==='ninguno'||x.includes('ningun'))return'Sin material';if(x.includes('pelot'))return'Pelota';if(x.includes('aro'))return'Aros';if(x.includes('cono'))return'Conos';if(x.includes('cuerda'))return'Cuerdas';if(x.includes('tarjet'))return'Tarjetas';if(x.includes('pañuel')||x.includes('panuel'))return'Pañuelos';return m||'Otros'}
function intensity(g){const x=norm((g.description||'')+' '+(g.title||''));if(/velocidad|sprint|resistencia|carrera|perseguir|pillar|relevos|salidas/.test(x))return'Alta';if(/relaj|vuelta a la calma|estir/.test(x))return'Baja';return g.intensity||'Media'}
function buildFilters(){const c=[['#ageFilters',['Infantil','Primaria','1º-2º ESO','12-13 años','6º Primaria']],['#materialFilters',['Sin material','Pelota','Aros','Conos','Cuerdas','Tarjetas','Pañuelos']],['#spaceFilters',['Pista / gimnasio','Exterior','Aula','Espacio reducido']],['#intensityFilters',['Baja','Media','Alta']]];for(const [sel,opts]of c){const e=$(sel);if(e)e.innerHTML=opts.map(o=>`<label class="check"><input type="checkbox" value="${esc(o)}"> ${esc(o)}</label>`).join('')}$$('.filters input').forEach(x=>x.addEventListener('change',renderGames))}
function selected(sel){return $$(sel+' input:checked').map(x=>x.value)}
function matches(g){const q=norm(val('search')),t=norm([g.title,g.description,g.material,g.age,g.source].join(' '));if(q&&!t.includes(q))return false;const a=selected('#ageFilters'),m=selected('#materialFilters'),s=selected('#spaceFilters'),i=selected('#intensityFilters');return(!a.length||a.some(v=>norm(g.age).includes(norm(v))))&&(!m.length||m.includes(materialTag(g.material)))&&(!s.length||s.includes(g.space))&&(!i.length||i.includes(intensity(g)))}
function renderGames(){let list=games.filter(matches),sort=val('sort');if(sort==='az')list.sort((a,b)=>(a.title||'').localeCompare(b.title||'','es'));if(sort==='za')list.sort((a,b)=>(b.title||'').localeCompare(a.title||'','es'));if($('#resultSummary'))$('#resultSummary').textContent=`${list.length} juego${list.length===1?'':'s'} encontrados`;const grid=$('#gameGrid'),tpl=$('#gameCardTemplate');if(!grid||!tpl)return;grid.innerHTML='';list.forEach(g=>{const n=tpl.content.cloneNode(true),card=n.querySelector('.game-card');card.dataset.id=g.id;card.querySelector('.age').textContent=g.age||'Edad variable';card.querySelector('.ocr-badge').classList.toggle('hidden',!g.needsReview);card.querySelector('h3').textContent=g.title||'Juego sin título';card.querySelector('.desc').textContent=g.description||'';card.querySelector('.material').textContent=materialTag(g.material);card.querySelector('.space').textContent=g.space||'—';card.querySelector('.intensity').textContent=intensity(g);card.querySelector('.source').textContent=`${g.source||'Fuente no indicada'} · pág. ${g.page||'—'}`;card.querySelector('.add-btn').onclick=e=>{e.stopPropagation();addToSession(g.id)};card.querySelector('.details').onclick=e=>{e.stopPropagation();openGame(g.id)};card.onclick=()=>openGame(g.id);grid.appendChild(n)});$('#empty')?.classList.toggle('hidden',list.length>0)}
function openGame(id){const g=games.find(x=>x.id===id);if(!g||!$('#dialogContent'))return;$('#dialogContent').innerHTML=`<div class="eyebrow">FICHA DE JUEGO</div><h2>${esc(g.title)}</h2><div class="detail-meta"><span class="tag">${esc(g.age||'Edad variable')}</span><span class="chip">${esc(materialTag(g.material))}</span><span class="chip">${esc(g.space||'—')}</span><span class="chip">${esc(intensity(g))}</span></div><p class="detail-desc">${esc(g.description||'')}</p><div class="source-box"><strong>Fuente</strong><br>${esc(g.source||'Fuente no indicada')} · página ${esc(g.page||'—')}<br><small>Material original: ${esc(g.material||'—')}</small></div><div style="display:flex;gap:10px;margin-top:18px"><button class="primary" id="dialogAdd">Añadir a sesión</button><button class="ghost" id="dialogClose">Cerrar</button></div>`;$('#dialogAdd').onclick=()=>{addToSession(g.id);$('#gameDialog')?.close()};$('#dialogClose').onclick=()=>$('#gameDialog')?.close();$('#gameDialog')?.showModal()}
function addToSession(id){if(!session.some(x=>x.id===id))session.push({id,phase:'Sin asignar',minutes:'',note:''});renderSession();if($('#sessionCount'))$('#sessionCount').textContent=session.length}
function removeFromSession(i){session.splice(i,1);renderSession();if($('#sessionCount'))$('#sessionCount').textContent=session.length}
function phaseOptions(c){return['Sin asignar','Calentamiento','Parte principal','Vuelta a la calma'].map(p=>`<option ${p===c?'selected':''}>${p}</option>`).join('')}
function renderSession(){const box=$('#sessionList');if(!box)return;box.innerHTML='';if(!session.length){box.innerHTML='<div class="dropzone" id="dropzone">Arrastra aquí juegos para empezar</div>';bindDrop();return}session.forEach((item,i)=>{const g=games.find(x=>x.id===item.id);if(!g)return;const el=document.createElement('div');el.className='session-item';el.draggable=true;el.innerHTML=`<div class="drag">☷</div><div><h4>${esc(i+1+'. '+(g.title||'Juego'))}</h4><p>${esc(g.age||'')} · ${esc(materialTag(g.material))}</p><div class="session-total">${esc(item.note||'')}</div></div><div class="session-controls"><select class="phase">${phaseOptions(item.phase||'Sin asignar')}</select><input class="minutes" type="number" min="1" placeholder="min" value="${esc(item.minutes||'')}"><input class="note" placeholder="Variante / observación" value="${esc(item.note||'')}"></div><button class="remove">×</button>`;el.querySelector('.phase').onchange=e=>item.phase=e.target.value;el.querySelector('.minutes').onchange=e=>item.minutes=e.target.value;el.querySelector('.note').oninput=e=>{item.note=e.target.value;el.querySelector('.session-total').textContent=e.target.value};el.querySelector('.remove').onclick=()=>removeFromSession(i);el.ondragstart=e=>e.dataTransfer.setData('text/plain',JSON.stringify({id:item.id,from:i}));el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();try{const d=JSON.parse(e.dataTransfer.getData('text/plain'));if(d.from!==undefined){const moved=session.splice(d.from,1)[0];session.splice(i,0,moved);renderSession()}}catch(_){}};box.appendChild(el)});const dz=document.createElement('div');dz.className='dropzone';dz.id='dropzone';dz.textContent='Suelta aquí para añadir otro juego';box.appendChild(dz);bindDrop()}
function bindDrop(){const dz=$('#dropzone');if(!dz)return;dz.ondragover=e=>e.preventDefault();dz.ondrop=e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/plain');try{const d=JSON.parse(raw);if(d.id)addToSession(d.id)}catch(_){if(raw)addToSession(raw)}}}
function autoPhase(){if(!session.length)return;session.forEach((x,i)=>{x.phase=i===0?'Calentamiento':(i===session.length-1&&session.length>2?'Vuelta a la calma':'Parte principal');if(!x.minutes)x.minutes=i===0?'10':(i===session.length-1?'5':'10')});renderSession()}
function renderSaved(){const el=$('#savedList');if(!el)return;el.innerHTML=savedSessions.length?'':'<p class="muted">Aún no hay sesiones guardadas.</p>';savedSessions.forEach(s=>{const d=document.createElement('div');d.className='saved-card';d.innerHTML=`<strong>${esc(s.name||'Sesión sin nombre')}</strong><small>${esc(s.date||'')} · ${esc(s.group||'Sin grupo')} · ${(s.games||[]).length} juegos</small><button>Recuperar</button>`;d.querySelector('button').onclick=()=>{session=(s.games||[]).map(x=>typeof x==='string'?{id:x,phase:'Sin asignar',minutes:'',note:''}:x);setVal('sessionName',s.name||'');setVal('sessionDate',s.date||'');setVal('sessionGroup',s.group||'');renderSession();switchView('builder');if($('#sessionCount'))$('#sessionCount').textContent=session.length};el.appendChild(d)})}
function renderSources(){const e=$('#sourcesList');if(!e)return;e.innerHTML=sources.map(s=>`<div class="source-row"><strong>${esc(s.display||s.name||'Fuente')}</strong><small>${esc(s.name||'')} · ${s.pages||'—'} páginas · ${esc(s.type||'')}</small></div>`).join('')}
function switchView(v){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#libraryView')?.classList.toggle('hidden',v!=='library');$('#builderView')?.classList.toggle('hidden',v!=='builder')}
$('#search')?.addEventListener('input',renderGames);$('#sort')?.addEventListener('change',renderGames);$('#filterToggle')?.addEventListener('click',()=>$('#filters')?.classList.toggle('open'));$('#clearFilters')?.addEventListener('click',()=>{$$('.filters input').forEach(x=>x.checked=false);setVal('search','');renderGames()});$$('.tab').forEach(x=>x.addEventListener('click',()=>switchView(x.dataset.view)));$('#newSessionBtn')?.addEventListener('click',()=>{switchView('builder');session=[];setVal('sessionName','');setVal('sessionGroup','');setVal('sessionDate',new Date().toISOString().slice(0,10));renderSession();if($('#sessionCount'))$('#sessionCount').textContent=0});$('#saveSession')?.addEventListener('click',()=>{savedSessions.unshift({name:val('sessionName').trim(),date:val('sessionDate'),group:val('sessionGroup').trim(),games:[...session]});localStorage.setItem('motorlab_sessions',JSON.stringify(savedSessions));renderSaved();alert('Sesión guardada.')});$('#printSession')?.addEventListener('click',()=>window.print());$('#autoPhaseBtn')?.addEventListener('click',autoPhase);$('#sourcesBtn')?.addEventListener('click',()=>$('#sourcesDialog')?.showModal());document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search')?.focus()}});init();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
